[metadata.heroku]
  root-package = "github.com/phpCoder88/golang-test"
  go-version = "go1.16.3"
  install = [ "./cmd/..." ]
  ensure = "false"
  additional-tools = ["github.com/golang-migrate/migrate@v3.4.0"]
